#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use \Reaver\Spider;
use \Dotenv\Dotenv;
use Illuminate\Database\Capsule\Manager as Capsule;

parse_str(implode('&', array_slice($argv, 1)), $_GET);

/**
 * Loads the environment variables.
 * This was originally set up to follow more cli like crawlers that implement a 
 * config file. Currently this isn't being implemented as users can input the
 * url directly to the cli.
 * @var Dotenv
 */

$dotenv = new Dotenv(__DIR__);
$dotenv->load();

$capsule = new Capsule;

$capsule->addConnection([
    'driver'    => 'mysql',
    'host'      => getenv('DB_HOST'),
    'database'  => getenv('DATABASE'),
    'username'  => getenv('DB_USER'),
    'password'  => getenv('DB_PASS'),
    'charset'   => 'utf8',
    'collation' => 'utf8_unicode_ci',
    'prefix'    => '',
    'port'      => getenv('DB_PORT')
]);

// Make this Capsule instance available globally via static methods
$capsule->setAsGlobal();

// Setup the Eloquent ORM
$capsule->bootEloquent();


/**
 * Create new to spider
 * @var Spider
 */
$crawler = new Spider;
// Set the url through the the cli.
$crawler->init();
