#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use \Reaver\Spider;
use \Dotenv\Dotenv;

$dotenv = new Dotenv(__DIR__);
$dotenv->load();

$crawler = new Spider;

$crawler->setUrl($argv[1]);

$crawler->fetch();

$crawler->follow();

$crawler->stats();